### ISSUE TITLE
Command npm run web stopped with error code 1

### ISSUE THREAD

**Issue by fcantenot** [gismofx/BlazorSignaturePad#3]
I have an error message "npm run web stopped with error code 1" during compilation of the project "BlazorSignaturePad" (line 42 .csproj file)
![Capture d’écran 2023-08-16 100430](https://github.com/gismofx/BlazorSignaturePad/assets/82578242/0e3916d3-caa1-4079-aa2a-ba9296d54427)
Thanks

**Comment by gismofx** [comment]
I'll have a look this evening and fix this up.

**Comment by gismofx** [comment]
@fcantenot Do you have NPM workload installed in Visual Studio? Check via Visual Studio Installer and make sure "Node.js development" is checked. 

I'm running on my end and not get any errors.

**Comment by fcantenot** [comment]
@gismofx thanks for your quick answer,  it seems to me everything is good !
![nodejs](https://github.com/gismofx/BlazorSignaturePad/assets/82578242/a2629521-f678-4f16-a21b-a325af9bf30c)

I have a Nuget package "Microsoft.AspNetCore.Components.Web" version 5.0.7 and I can't update it to version 7.0.10.
Do you think my issue can come from this package ?

**Comment by fcantenot** [comment]
@gismofx I updated framework .NET from 6.0 to 7.0. I removed and installed "Microsoft.AspNetCore.Components.Web" but I still have an error when I want to compile "BlazorSignaturePad"
![nodejs](https://github.com/gismofx/BlazorSignaturePad/assets/82578242/71747a7b-8f25-4c23-99f7-6fcb8d912eb0)

**Comment by fcantenot** [comment]
@gismofx I searched on internet and I found this solution -> "npm install react-scripts@latest" 
Now it works !

Thanks

**Comment by gismofx** [comment]
Glad you figured it out! If you find any way to make the config scripts more robust :), let me know. If anything else, please open a new issue.
